app:
  build: .
  command: 'bash -c ''bundle exec puma -e production -C config/puma.rb'''
  container_name: calico_app
  restart: always
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: production
    PG_HOST: postgresql
    PG_USER: calico
    PG_PASSWORD: calico
    PG_PORT: 5432
    SECRET_KEY_BASE: 'GNeBhAoT81xWAlRls7NJa1zZjZ/BTJ9EMGO+YcMh/8/+Xu9R6jzAWk/uUZIYEDuoIK19vwesRA5SQPVJow6dxQ=='
  links:
    - postgresql
postgresql:
  image: postgres:9.5.3
  container_name: calico_db
  restart: always
  environment:
    POSTGRES_USER: calico
    POSTGRES_DB: ca_production
    POSTGRES_PASSWORD: calico
nginx:
  build: .
  dockerfile: ./docker/Dockerfile.nginx
  container_name: calico_nginx
  restart: always
  ports:
    - "80:80"
  links:
    - app
