app:
  image: casecommons/calico_app
  container_name: calico_app
  restart: always
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: production
    PG_HOST: postgresql
    PG_USER: calico
    PG_PASSWORD: calico
    PG_PORT: 5432
  links:
    - postgresql
postgresql:
  image: postgres:9.5.3
  container_name: calico_db
  restart: always
  environment:
    POSTGRES_USER: calico
    POSTGRES_DB: ca_production
    POSTGRES_PASSWORD: calico
nginx:
  image: casecommons/calico_nginx
  container_name: calico_nginx
  restart: always
  ports:
    - "80:80"
  links:
    - app
