app:
  build: .
  dockerfile: Dockerfile
  container_name: calico
  restart: always
  environment:
    PG_HOST: postgresql
    PG_USER: calico
    PG_PORT: 5432
  links:
    - postgresql
postgresql:
  image: postgres:9.5.3
  container_name: postgres
  restart: always
  environment:
    POSTGRES_USER: calico
