app:
  build: .
  command: 'bash -c ''bundle exec puma -e development -C config/puma.rb'''
  container_name: calico_app
  restart: always
  environment:
    RAILS_ENV: development
    PG_HOST: postgresql
    PG_USER: calico
    PG_PASSWORD: calico
    PG_PORT: 5432
    PORT: 3000
  ports:
    - "3000:3000"
    - "4857:4857"
  links:
    - postgresql
postgresql:
  image: postgres:9.5.3
  container_name: calico_db
  restart: always
  environment:
    POSTGRES_USER: calico
    POSTGRES_DB: ca_development
    POSTGRES_PASSWORD: calico
nginx:
  build: .
  dockerfile: ./docker/Dockerfile.nginx
  container_name: calico_nginx
  restart: always
  ports:
    - "80:80"
  links:
    - app
