default: &default
  adapter: postgresql
  username: <%= ENV['PG_USER'] || 'casebook' %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  password:
  encoding: utf8
  prepared_statements: false
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ca_development

test:
  <<: *default
  database: ca_test

production:
  <<: *default
  database: ca_production
