default: &default
  adapter: postgresql
  username: <%= ENV['PG_USER'] || 'calico' %>
  port: <%= ENV['PG_PORT'] || 5432 %>
  password: <%= ENV['PG_PASSWORD'] %>
  encoding: utf8
  prepared_statements: false
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  database: <%= ENV['PG_DB'] || 'ca_development' %>

test:
  <<: *default
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  database: <%= ENV['PG_DB'] || 'ca_test' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: ca_production
