ruby_version: 'ruby-2.2.3'
bundler_version: 1.12.5
hooks:
  pre_setup: npm install
  worker_setup: bundle exec rake db:setup  # Runs once for each worker to do, e.g., database setup
test_pattern:
  - spec/**/*_spec.rb
tests:
  - bundle exec rake rspec
:environment:
  'RAILS_ENV': 'test'
:nodejs:
  version: '0.10.31'
:postgresql:
  :version: '9.5'
