ruby_version: 'ruby-2.2.3'
bundler_version: 1.12.5
hooks:
  worker_setup: bundle exec rake db:setup  # Runs once for each worker to do, e.g., database setup
test_pattern:
  - spec/**/*_spec.rb
tests:
  - name: rspec_tests
    command: bundle exec rake rspec
:environment:
  'RAILS_ENV': 'test'
:postgresql:
  :version: '9.5'
  :shards: 3
